import { Resend } from "resend";

// Validate that the API key is available
const apiKey = process.env.RESEND_API_KEY;

if (!apiKey) {
  console.error("RESEND_API_KEY environment variable is not set");
  throw new Error("RESEND_API_KEY environment variable is required");
}

export const resend = new Resend(apiKey);

export interface EmailData {
  email: string;
  toolName: string;
  userAgent?: string;
  timestamp?: string;
}

export interface WelcomeEmailData {
  email: string;
  toolName?: string;
}

export interface EventSubscriptionData {
  email: string;
  eventTitle: string;
  eventId: string;
  eventDate?: string;
  timestamp?: string;
}

export interface InsightsSubscriptionData {
  email: string;
  userAgent?: string;
  timestamp?: string;
}

export interface EventSubscriptionWelcomeData {
  email: string;
  eventTitle: string;
  eventDate?: string;
}

export const sendEmailNotification = async (data: EmailData) => {
  try {
    console.warn("Sending email notification to:", "anika.leila@drexus.com");
    console.warn("Email data:", { toolName: data.toolName, email: data.email });

    const result = await resend.emails.send({
      from: "New Drexus Subscription <noreply@notifications.drexus.com>",
      to: ["anika.leila@drexus.com", "s@drexus.com"], // Replace with your actual email
      subject: `New ${data.toolName} Email Capture`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">New Email Capture from Drexus Footer Newsletter Subscription</h2>

          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #374151; margin-top: 0;">Capture Details</h3>
            <p><strong>Tool:</strong> ${data.toolName}</p>
            <p><strong>Email:</strong> ${data.email}</p>
            <p><strong>Timestamp:</strong> ${data.timestamp || new Date().toISOString()}</p>
            ${data.userAgent ? `<p><strong>User Agent:</strong> ${data.userAgent}</p>` : ""}
          </div>

          <div style="background-color: #eff6ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
            <p style="margin: 0; color: #1e40af;">
              <strong>Next Steps:</strong> Follow up with this lead about ${data.toolName} and how Drexus can help their team.
            </p>
          </div>

          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
          <p style="color: #6b7280; font-size: 14px;">
            This email was automatically generated by the Drexus website contact form.
          </p>
        </div>
      `,
    });

    console.warn("Email notification sent successfully:", result);
    return { success: true, data: result };
  } catch (error) {
    console.error("Error sending email notification:", error);
    console.error("Error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
      name: error instanceof Error ? error.name : undefined,
    });
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
};

export const sendWelcomeEmail = async (data: WelcomeEmailData) => {
  try {
    console.warn("Sending welcome email to:", data.email);
    console.warn("Welcome email data:", { toolName: data.toolName });

    const result = await resend.emails.send({
      from: "Drexus <welcome@notifications.drexus.com>",
      to: [data.email],
      subject: "Welcome to Drexus - Your Strategic Edge Awaits",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #1e3a8a; font-size: 28px; margin-bottom: 10px;">Welcome to the Drexus Community!</h1>
            <p style="color: #6b7280; font-size: 16px;">Strategic technology partnerships that accelerate growth</p>
          </div>

          <div style="background: #f8fafc; border-radius: 8px; margin-bottom: 20px; text-align: left;">
            <div style="padding: 20px 20px 20px 0;">
              <h2 style="color: #1e3a8a; font-size: 20px; margin-bottom: 15px; text-align: left; margin-left: 0; padding-left: 0;">You're Now Part of Something Bigger</h2>
              <p style="color: #374151; line-height: 1.6; margin-bottom: 15px; text-align: left; margin-left: 0; padding-left: 0;">
                Thank you for joining our community of ambitious leaders who understand that technology isn't just about tools—it's about strategic advantage.
              </p>
              <p style="color: #374151; line-height: 1.6; text-align: left; margin-left: 0; padding-left: 0;">
                As a Drexus subscriber, you'll get exclusive access to the insights, frameworks, and strategic thinking that help companies like yours scale without the typical growing pains.
              </p>
            </div>
          </div>

          <div style="margin-bottom: 20px;">
            <h3 style="color: #1e3a8a; font-size: 18px; margin-bottom: 15px;">What You'll Receive Every Week:</h3>
            <ul style="color: #374151; line-height: 1.6; padding-left: 20px;">
              <li><strong>Strategic Technology Insights:</strong> Deep dives into emerging tech that matters for your business</li>
              <li><strong>Market Intelligence:</strong> Trends and opportunities before they become mainstream</li>
              <li><strong>Engineering Excellence:</strong> Best practices from our work with 100+ companies</li>
              <li><strong>Growth Frameworks:</strong> Proven strategies for scaling without breaking</li>
              <li><strong>Exclusive Tools:</strong> Early access to our proprietary assessment tools and calculators</li>
            </ul>
          </div>

          <div style="background: #eff6ff; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6; margin-bottom: 20px;">
            <h3 style="color: #1e3a8a; font-size: 16px; margin-bottom: 10px;">Ready to Accelerate Your Growth?</h3>
            <p style="color: #374151; line-height: 1.6; margin-bottom: 15px;">
              While you're here, explore our strategic tools and see how we've helped companies like yours achieve 3x faster time-to-market and 40% reduction in technical debt.
            </p>
            <div style="text-align: center;">
              <a href="https://drexus.com/tools"
                 style="background: #1e3a8a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: 600; margin-right: 10px;">
                Explore Our Tools
              </a>
            </div>
          </div>

          <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
            <p style="color: #9ca3af; font-size: 12px; margin-bottom: 5px;">
              You're receiving this because you subscribed to Drexus strategic insights.
            </p>
            <p style="color: #9ca3af; font-size: 12px;">
              <a href="https://drexus.com/legal/privacy" style="color: #6b7280;">Privacy Policy</a>
            </p>
          </div>
        </div>
      `,
    });

    console.warn("Welcome email sent successfully:", result);
    return { success: true, data: result };
  } catch (error) {
    console.error("Error sending welcome email:", error);
    console.error("Welcome email error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
      name: error instanceof Error ? error.name : undefined,
    });
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
};

export const sendEventSubscriptionNotification = async (data: EventSubscriptionData) => {
  try {
    console.warn("Sending event subscription notification to:", "anika.leila@drexus.com");
    console.warn("Event subscription data:", { eventTitle: data.eventTitle, email: data.email });

    const result = await resend.emails.send({
      from: "New Event Subscription <noreply@notifications.drexus.com>",
      to: ["anika.leila@drexus.com", "s@drexus.com"], // Replace with your actual email
      subject: `New Event Subscription: ${data.eventTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">New Event Subscription from Drexus Events</h2>

          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #374151; margin-top: 0;">Subscription Details</h3>
            <p><strong>Event:</strong> ${data.eventTitle}</p>
            <p><strong>Event ID:</strong> ${data.eventId}</p>
            <p><strong>Email:</strong> ${data.email}</p>
            <p><strong>Timestamp:</strong> ${data.timestamp || new Date().toISOString()}</p>
            ${data.eventDate ? `<p><strong>Event Date:</strong> ${data.eventDate}</p>` : ""}
          </div>

          <div style="background-color: #eff6ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
            <p style="margin: 0; color: #1e40af;">
              <strong>Next Steps:</strong> This user is interested in events and wants to be notified about future events. Consider adding them to your event marketing list.
            </p>
          </div>

          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
          <p style="color: #6b7280; font-size: 14px;">
            This email was automatically generated by the Drexus website event subscription form.
          </p>
        </div>
      `,
    });

    console.warn("Event subscription notification sent successfully:", result);
    return { success: true, data: result };
  } catch (error) {
    console.error("Error sending event subscription notification:", error);
    console.error("Error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
      name: error instanceof Error ? error.name : undefined,
    });
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
};

export const sendInsightsSubscriptionNotification = async (data: InsightsSubscriptionData) => {
  try {
    console.warn("Sending insights subscription notification to:", "anika.leila@drexus.com");
    console.warn("Insights subscription data:", { email: data.email });

    const result = await resend.emails.send({
      from: "New Insights Subscription <noreply@notifications.drexus.com>",
      to: ["anika.leila@drexus.com", "s@drexus.com"], // Replace with your actual email
      subject: `New Insights Newsletter Subscription`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">New Insights Newsletter Subscription</h2>

          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #374151; margin-top: 0;">Subscription Details</h3>
            <p><strong>Email:</strong> ${data.email}</p>
            <p><strong>Subscription Type:</strong> Weekly Insights Newsletter</p>
            <p><strong>Timestamp:</strong> ${data.timestamp || new Date().toISOString()}</p>
            ${data.userAgent ? `<p><strong>User Agent:</strong> ${data.userAgent}</p>` : ""}
          </div>

          <div style="background-color: #eff6ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
            <p style="margin: 0; color: #1e40af;">
              <strong>What they'll receive:</strong> Weekly notifications about new insights, frameworks, and research added to the website.
            </p>
          </div>

          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
          <p style="color: #6b7280; font-size: 14px;">
            This email was automatically generated by the Drexus insights newsletter subscription.
          </p>
        </div>
      `,
    });

    console.warn("Insights subscription notification sent successfully:", result);
    return { success: true, data: result };
  } catch (error) {
    console.error("Error sending insights subscription notification:", error);
    console.error("Error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
      name: error instanceof Error ? error.name : undefined,
    });
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
};

export const sendEventSubscriptionWelcome = async (data: EventSubscriptionWelcomeData) => {
  try {
    console.warn("Sending event subscription welcome email to:", data.email);
    console.warn("Event subscription welcome data:", { eventTitle: data.eventTitle });

    const result = await resend.emails.send({
      from: "Drexus Events <events@notifications.drexus.com>",
      to: [data.email],
      subject: "You're subscribed! We'll remind you about future events",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #1e3a8a; font-size: 28px; margin-bottom: 10px;">You're All Set!</h1>
            <p style="color: #6b7280; font-size: 16px;">We'll remind you about future events and webinars</p>
          </div>

          <div style="background: #f8fafc; border-radius: 8px; margin-bottom: 20px; text-align: left;">
            <div style="padding: 20px 20px 20px 0;">
              <h2 style="color: #1e3a8a; font-size: 20px; margin-bottom: 15px; text-align: left; margin-left: 0; padding-left: 0;">Thank You for Subscribing</h2>
              <p style="color: #374151; line-height: 1.6; margin-bottom: 15px; text-align: left; margin-left: 0; padding-left: 0;">
                You've successfully subscribed to receive notifications about upcoming events and webinars from Drexus. Join 500+ technology leaders who trust our insights.
              </p>
              <p style="color: #374151; line-height: 1.6; text-align: left; margin-left: 0; padding-left: 0;">
                We'll send you timely reminders about events that match your interests, so you never miss out on valuable insights and networking opportunities.
              </p>
            </div>
          </div>

          <div style="margin-bottom: 20px;">
            <h3 style="color: #1e3a8a; font-size: 18px; margin-bottom: 15px;">What You'll Receive:</h3>
            <ul style="color: #374151; line-height: 1.6; padding-left: 20px;">
              <li><strong>Event Reminders:</strong> Get notified about upcoming webinars, workshops, and conferences</li>
              <li><strong>Early Access:</strong> Be the first to know about new events and exclusive content</li>
              <li><strong>Event Summaries:</strong> Receive key takeaways and recordings from events you might have missed</li>
              <li><strong>Speaker Spotlights:</strong> Learn about industry experts and thought leaders</li>
            </ul>
          </div>

          <div style="background: #eff6ff; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6; margin-bottom: 20px;">
            <h3 style="color: #1e3a8a; font-size: 16px; margin-bottom: 10px;">Explore Our Events</h3>
            <p style="color: #374151; line-height: 1.6; margin-bottom: 15px;">
              While you're here, check out our upcoming events and see what's coming next in the world of strategic technology.
            </p>
            <div style="text-align: center;">
              <a href="https://drexus.com/events"
                 style="background: #1e3a8a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: 600; margin-right: 10px;">
                View All Events
              </a>
            </div>
          </div>

          <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
            <p style="color: #9ca3af; font-size: 12px; margin-bottom: 5px;">
              You're receiving this because you subscribed to Drexus event notifications.
            </p>
            <p style="color: #9ca3af; font-size: 12px;">
              <a href="https://drexus.com/legal/privacy" style="color: #6b7280;">Privacy Policy</a>
            </p>
          </div>
        </div>
      `,
    });

    console.warn("Event subscription welcome email sent successfully:", result);
    return { success: true, data: result };
  } catch (error) {
    console.error("Error sending event subscription welcome email:", error);
    console.error("Event subscription welcome email error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
      name: error instanceof Error ? error.name : undefined,
    });
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
};

export const sendInsightsWelcomeEmail = async (data: InsightsSubscriptionData) => {
  try {
    console.warn("Sending insights welcome email to:", data.email);

    const result = await resend.emails.send({
      from: "Drexus Insights <insights@notifications.drexus.com>",
      to: [data.email],
      subject: "Welcome to Drexus Insights - Your Weekly Strategic Edge",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #1e3a8a; font-size: 28px; margin-bottom: 10px;">Welcome to Drexus Insights!</h1>
            <p style="color: #6b7280; font-size: 16px;">Strategic frameworks and research delivered weekly</p>
          </div>

          <div style="background: #f8fafc; border-radius: 8px; margin-bottom: 20px; text-align: left;">
            <div style="padding: 20px;">
              <h2 style="color: #1e3a8a; font-size: 20px; margin-bottom: 15px;">What You'll Receive</h2>
              <ul style="color: #374151; line-height: 1.8; margin: 0; padding-left: 20px;">
                <li><strong>Weekly insights</strong> on emerging technologies and market trends</li>
                <li><strong>Actionable frameworks</strong> from our work with 100+ companies</li>
                <li><strong>Strategic research</strong> to accelerate your business growth</li>
                <li><strong>Early access</strong> to new content and resources</li>
              </ul>
            </div>
          </div>

          <div style="background: #eff6ff; border-radius: 8px; margin-bottom: 20px; text-align: left;">
            <div style="padding: 20px;">
              <h3 style="color: #1e3a8a; font-size: 18px; margin-bottom: 10px;">📅 Delivery Schedule</h3>
              <p style="color: #374151; line-height: 1.6; margin: 0;">
                Every Friday, you'll receive our curated insights directly in your inbox. No fluff, no sales pitches—just proven strategies that work.
              </p>
            </div>
          </div>

          <div style="text-align: center; margin: 30px 0;">
            <a href="https://drexus.com/insights" style="background: #1e3a8a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600; display: inline-block;">
              Browse Current Insights
            </a>
          </div>

          <div style="border-top: 1px solid #e5e7eb; padding-top: 20px; margin-top: 30px;">
            <p style="color: #6b7280; font-size: 14px; line-height: 1.6; margin: 0;">
              <strong>Questions?</strong> Reply to this email anytime. We read every message and love hearing from our community.
            </p>
          </div>
        </div>
      `,
    });

    console.warn("Insights welcome email sent successfully:", result);
    return { success: true, data: result };
  } catch (error) {
    console.error("Error sending insights welcome email:", error);
    console.error("Error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
      name: error instanceof Error ? error.name : undefined,
    });
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
};
